
local tint_colors = {
  ["blue"]     = { util.color("#1560bd") },
  ["brown"]    = { r = 67, g = 70, b = 75 },
  ["cyan"]     = { util.color("#00BCE3") },
  ["green"]    = { util.color("#006E33") },
  ["grey"]     = { r = 136, g = 139, b = 141 },
  ["lgrey"]    = { r = 219, g = 226, b = 233 },
  ["dgrey"]    = { r = 123, g = 134, b = 122, a = 0.9 },
  ["orange"]   = { util.color("#CB6015") },
  ["lpurple"]  = { util.color("#B946F2") },
  ["purple"]   = { util.color("#8031A7") },
  ["dpurple"]  = { r = 101, g = 85, b = 177, a = 0.8 },
  ["red"]      = { util.color("#AB2328") },
  ["teal"]     = { util.color("#00B2A9") },
  ["lyellow"]  = { util.color("#FEDD00") },
  ["yellow"]   = { util.color("#FEDD00") },

  ["brass"]    = { util.color("#AC9F3C") },
  ["bronze"]   = { util.color("#a97142") },
  ["glass"]    = { util.color("#afeeee") },
  ["gold"]     = { util.color("#FFB81C") },
  ["chrome"]   = { util.color("#DBE2E9") },
  ["platinum"] = { util.color("#E5E1E6") },
  ["zinc"]     = { util.color("#BAC4C8") },
  ["titan"]    = { util.color("#DADBCF") },
  ["nickel"]   = { util.color("#CCD3D8") },
  ["mangan"]   = { util.color("#D3BC8D") },
}

--TODO: key name should be mod_prefix-item_type
return {
  adamantite          = tint_colors["purple"],
  aluminum            = tint_colors["lgrey"],
  aluminium           = tint_colors["lgrey"],
  antitate            = tint_colors["red"],
  brass               = tint_colors["yellow"],
  bronze              = tint_colors["yellow"],
  chromium            = tint_colors["grey"],
  cobalt              = tint_colors["blue"],
  copper              = tint_colors["orange"],
  ["cobalt-steel"]    = tint_colors["blue"],
  ["copper-tungsten"] = tint_colors["red"],
  elionagate          = tint_colors["teal"],
  -- glass            = tint_colors["glass"]
  gold                = tint_colors["yellow"],
  gunmetal            = tint_colors["yellow"],
  imersium            = tint_colors["purple"],
  invar               = tint_colors["grey"],
  iron                = tint_colors["grey"],
  lead                = tint_colors["brown"],
  lithium             = tint_colors["dgrey"],
  manganic            = tint_colors["orange"],
  ["meta-garnierite"] = tint_colors["yellow"],
  nickel              = tint_colors["grey"],
  nitinol             = tint_colors["grey"],
  ["nova-leucoxene"]  = tint_colors["dgrey"],
  orichalcite         = tint_colors["orange"],
  osmium              = tint_colors["purple"],
  phosphic            = tint_colors["teal"],
  phosphorite         = tint_colors["grey"],
  plumbic             = tint_colors["purple"],
  ["pro-galena"]      = tint_colors["dgrey"],
  sanguinate          = tint_colors["red"],
  silicon             = tint_colors["brown"],
  silver              = tint_colors["grey"],
  stannic             = tint_colors["green"],
  steel               = tint_colors["grey"],
  tellurium           = tint_colors["purple"],
  tin                 = tint_colors["grey"],
  titanic             = tint_colors["grey"],
  titanium            = tint_colors["dgrey"],
  tungsten            = tint_colors["dpurple"],
  zinc                = tint_colors["grey"],
}

