return { -- color, icon/sprite-variation
  adamantite          = { "purple", 1 },
  aluminum            = { "lgrey", r = 219, g = 226, b = 233 },
  aluminium           = { "lgrey", r = 219, g = 226, b = 233 },
  antitate            = { "red", 1 },
  brass               = { "yellow", 1 },
  bronze              = { "yellow", 2 },
  chromium            = { "grey", 1 },
  cobalt              = { "blue", 2 },
  copper              = { "orange", 1 },
  ["cobalt-steel"]    = { "blue", 1 },
  ["copper-tungsten"] = { "red", 2 },
  elionagate          = { "teal", 1 },
  -- glass            = {"purple", 1},
  gold                = { "yellow", 2 },
  gunmetal            = { "yellow", 2 },
  imersium            = { "purple", 1 },
  invar               = { "grey", 3 },
  iron                = { "grey", r = 168, g = 169, b = 173 },
  lead                = { "brown", r = 67, g = 70, b = 75 },
  lithium             = { "dgrey", r = 123, g = 134, b = 122, a = 1 },
  manganic            = { "orange", 3 },
  ["meta-garnierite"] = { "yellow", 1 },
  nickel              = { "grey", 2 },
  nitinol             = { "grey", 2 },
  ["nova-leucoxene"]  = { "dgrey", 1 },
  orichalcite         = { "orange", 1 },
  osmium              = { "purple", 3 },
  phosphic            = { "teal", 3 },
  phosphorite         = { "grey", 1 },
  plumbic             = { "purple", 3 },
  ["pro-galena"]      = { "dgrey", 1 },
  sanguinate          = { "red", 1 },
  silicon             = { "brown", 1 },
  silver              = { "grey", 1 },
  stannic             = { "green", 3 },
  steel               = { "grey", r = 136, g = 139, b = 141 },
  tellurium           = { "purple", 1 },
  tin                 = { "grey", 2 },
  titanic             = { "grey", 3 },
  titanium            = { "dgrey", 2 },
  tungsten            = { "dpurple", r = 101, g = 85, b = 177, a = 1 },
  zinc                = { "grey", 2 },
}
