data:extend({
    {
        type = "int-setting",
        name = "yis-needed",
        localised_name = { "", "[img=sum-symbol]", " - ", { "mod-setting-name.yis-needed" } },
        setting_type = "startup",
        minimum_value = 1,
        default_value = 5,
        order = "a",
    },
    {
        type = "int-setting",
        name = "yis-probability",
        localised_name = { "", "[img=percent-symbol]", " - ", { "mod-setting-name.yis-probability" } },
        setting_type = "startup",
        minimum_value = 0,
        maximum_value = 100,
        default_value = 24,
        order = "b",
    },
    -- {
    --     hidden = true,
    --     type = "string-setting",
    --     name = "yis-amount-method",
    --     setting_type = "startup",
    --     default_value = "al",
    --     allowed_values = { "cu", "cl", "au", "al" }
    -- },
    {
        hidden = false,
        type = "bool-setting",
        name = "yis-amount-range",
        localised_name = { "", "[img=fixed-symbol]", " - ", { "mod-setting-name.yis-amount-range" } },
        setting_type = "startup",
        default_value = true,
        order = "c",
    },
    {
        hidden = false,
        type = "bool-setting",
        name = "yis-amount-limit",
        localised_name = { "", "[img=sigma-symbol]", " - ", { "mod-setting-name.yis-amount-limit" } },
        setting_type = "startup",
        default_value = true,
        order = "d",
    },
    -- {
    --     type = "string-setting",
    --     name = "yis-unlock-scraps",
    --     localised_name = { "", "[img=unlock-symbol]", " - ", { "mod-setting-name.yis-unlock-scraps" } },
    --     setting_type = "startup",
    --     default_value = "iron-scrap, copper-scrap",
    --     order = "e",
    -- },
    {
        hidden = true,
        type = "bool-setting",
        name = "yis-fluid-recipes",
        localised_name = { "", "[img=drop-symbol]", " - ", { "mod-setting-name.yis-fluid-recipes" } },
        setting_type = "startup",
        default_value = true,
        order = "z",
    },
    {
        hidden = true,
        type = "string-setting",
        name = "yis-uid",
        setting_type = "startup",
        default_value = "",
        allow_blank = true,
    },
})
