data:extend({
    {
        type = "int-setting",
        name = "yis-needed",
        localised_name = { "", "[img=sum-symbol]", " - ", { "mod-setting-name.yis-needed" } },
        setting_type = "startup",
        minimum_value = 1,
        default_value = 5,
        order = "a",
    },
    {
        type = "int-setting",
        name = "yis-probability",
        localised_name = { "", "[img=percent-symbol]", " - ", { "mod-setting-name.yis-probability" } },
        setting_type = "startup",
        minimum_value = 0,
        maximum_value = 100,
        default_value = 24,
        order = "b",
    },
    {
        hidden = false,
        type = "bool-setting",
        name = "yis-fixed-amount",
        localised_name = { "", "[img=fixed-symbol]", " - ", { "mod-setting-name.yis-fixed-amount" } },
        setting_type = "startup",
        default_value = false,
        order = "c",
    },
    {
        hidden = false,
        type = "bool-setting",
        name = "yis-amount-limit",
        localised_name = { "", "[img=sigma-symbol]", " - ", { "mod-setting-name.yis-amount-limit" } },
        setting_type = "startup",
        default_value = true,
        order = "d",
    },

    {
        hidden = false,
        type = "bool-setting",
        name = "yis-shallow-log",
        localised_name = { "", "[img=gears-symbol]", " - ", { "mod-setting-name.yis-shallow-log" } },
        setting_type = "startup",
        default_value = true,
        order = "y",
    },
    {
        hidden = false,
        type = "bool-setting",
        name = "yis-fluid-recipes",
        localised_name = { "", "[img=drop-symbol]", " - ", { "mod-setting-name.yis-fluid-recipes" } },
        setting_type = "startup",
        default_value = true,
        order = "z",
    },
    {
        hidden = true,
        type = "bool-setting",
        name = "yis-barreling",
        setting_type = "startup",
        default_value = true,
    },
    {
        hidden = true,
        type = "bool-setting",
        name = "yis-IS_DEBUG",
        setting_type = "startup",
        default_value = false,
    },
})
