local graph = {}

local GENERATED_PREFIXES = { "yis-recycle-" }
local SIDE_CHAIN_TERMS = {
  "barrel",
  "barreling",
  "recycling",
  "void",
}

---Returns a numeric amount for an ingredient/result signature.
---@param entry table|nil
---@return number
function graph.amount_of(entry)
  if not entry then return 1 end
  if entry.amount ~= nil then return entry.amount end
  if entry.amount_min ~= nil and entry.amount_max ~= nil then
    return (entry.amount_min + entry.amount_max) / 2
  end
  return 1
end

---Returns true when a name starts with one of the listed generated prefixes.
---@param name string|nil
---@return boolean
local function starts_with_generated_prefix(name)
  if type(name) ~= "string" then return false end
  for _, prefix in ipairs(GENERATED_PREFIXES) do
    if name:sub(1, #prefix) == prefix then return true end
  end
  return false
end

---Returns true when a recipe is generated by Ingredient Scrap.
---@param recipe table|nil
---@return boolean
function graph.is_generated_recipe(recipe)
  return starts_with_generated_prefix(recipe and recipe.name)
end

---Returns true when a string contains any side-chain term.
---@param value string|nil
---@return boolean
local function contains_side_chain_term(value)
  if type(value) ~= "string" then return false end
  local lowered = string.lower(value)
  for _, term in ipairs(SIDE_CHAIN_TERMS) do
    if lowered:find(term, 1, true) then return true end
  end
  return false
end

---Returns true when a recipe should not be used as ancestry producer evidence.
---@param recipe table|nil
---@return boolean
function graph.looks_like_side_chain(recipe)
  if not recipe then return false end
  if recipe.category == "recycling" then return true end
  if type(recipe.name) == "string" and recipe.name:match("%-recycling$") then return true end
  return contains_side_chain_term(recipe.name) or contains_side_chain_term(recipe.category)
end

---Scores a producer recipe for ancestry resolution priority.
---@param recipe table
---@return integer
function graph.recipe_score(recipe)
  local score = 100
  if recipe.hidden == true then score = score - 30 end
  if recipe.enabled == false then score = score - 5 end
  if recipe.auto_recycle == false then score = score - 25 end
  if recipe.allow_decomposition == false then score = score - 10 end
  if graph.looks_like_side_chain(recipe) then score = score - 100 end

  local fluid_ingredients = 0
  for _, ingredient in ipairs(recipe.ingredients or {}) do
    if ingredient.type == "fluid" then fluid_ingredients = fluid_ingredients + 1 end
  end
  score = score - (fluid_ingredients * 6)
  score = score - math.max(#(recipe.ingredients or {}) - 4, 0)
  return score
end

---Builds item producer lists from the neutral production-flow dump.
---@param production_flow table
---@return table<string, table[]>
function graph.build_producers(production_flow)
  local producers = {}
  for _, recipe in pairs((production_flow and production_flow.recipes) or {}) do
    if not graph.is_generated_recipe(recipe) and not graph.looks_like_side_chain(recipe) then
      for _, result in ipairs(recipe.results or {}) do
        if (result.type or "item") == "item" and result.name then
          producers[result.name] = producers[result.name] or {}
          table.insert(producers[result.name], recipe)
        end
      end
    end
  end

  for _, recipe_list in pairs(producers) do
    table.sort(recipe_list, function(a, b)
      local score_a = graph.recipe_score(a)
      local score_b = graph.recipe_score(b)
      if score_a ~= score_b then return score_a > score_b end
      return (a.name or "") < (b.name or "")
    end)
  end

  return producers
end

---Returns the amount a recipe produces for a named item result.
---@param recipe table
---@param result_name string
---@return number
function graph.recipe_result_amount(recipe, result_name)
  for _, result in ipairs(recipe.results or {}) do
    if (result.type or "item") == "item" and result.name == result_name then
      return math.max(graph.amount_of(result), 1)
    end
  end
  return 1
end

return graph
