data:extend({
  {
    type = "tips-and-tricks-item-category",
    name = "ingredient-scrap",
    localised_name = { "tips-and-tricks-item-name.ingredient-scrap" },
    order = "j-[ingredient-scrap]",
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap",
    category = "ingredient-scrap",
    order = "a",
    is_title = true,
    starting_status = "unlocked",
    tag = "[item=yis-iron-scrap]",
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-generation",
    category = "ingredient-scrap",
    order = "b",
    indent = 1,
    starting_status = "unlocked",
    tag = "[item=yis-iron-scrap]",
    dependencies = { "ingredient-scrap" },
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-recycling",
    category = "ingredient-scrap",
    order = "c",
    indent = 1,
    starting_status = "unlocked",
    tag = "[recipe=yis-recycle-iron-scrap]",
    dependencies = { "ingredient-scrap-generation" },
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-mixed",
    category = "ingredient-scrap",
    order = "d",
    indent = 1,
    starting_status = "unlocked",
    tag = "[item=yis-mixed-scrap]",
    dependencies = { "ingredient-scrap-recycling" },
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-recycler",
    category = "ingredient-scrap",
    order = "e",
    indent = 1,
    starting_status = "unlocked",
    tag = "[entity=recycler]",
    dependencies = { "ingredient-scrap-mixed" },
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-fluid",
    category = "ingredient-scrap",
    order = "f",
    indent = 1,
    starting_status = "unlocked",
    tag = "[fluid=water]",
    dependencies = { "ingredient-scrap-recycling" },
  },
  {
    type = "tips-and-tricks-item",
    name = "ingredient-scrap-settings",
    category = "ingredient-scrap",
    order = "g",
    indent = 1,
    starting_status = "unlocked",
    tag = "[img=none]",
    dependencies = { "ingredient-scrap" },
  },
})
